### ISSUE TITLE
订阅的 rss 链接 内容更新后，软件中订阅内容还是之前的

### ISSUE THREAD

**Issue by mietl** [RSSNext/Follow#587]
### Describe the bug

订阅的 rss 链接 内容更新后，软件中订阅内容还是之前的，取消订阅后，重新订阅依旧一样，通过其他软件订阅可以看到最新的内容

### Feed Info

feedId: 53252940992479232
feedurl: https://mietl.github.io/atom.xml

### Reproduction Video

<img width="1487" alt="image" src="https://github.com/user-attachments/assets/3e265540-6aaa-40fc-bdec-3f30b05c3b1d">

<img width="439" alt="image" src="https://github.com/user-attachments/assets/51b20243-2c65-4c9f-945f-15ffd9d34d97">

### App Type

Web

### Version

0.0.1-alpha.16

### Operating System

macOS

### Browser Info

 Chrome: 129.0.6668.59

### Validations

- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.

### Contributions

- [ ] I am willing to submit a PR to fix this issue
- [ ] I am willing to submit a PR with failing tests (actually just go ahead and do it, thanks!)

**Comment by hyoban** [comment]
Related #290

**Comment by hyoban** [comment]
Fixed in the next release

**Comment by mietl** [comment]
### Environment

**App Version**: 0.0.1-alpha.18
**OS**: macOS
**User Agent**: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Follow/0.0.1-alpha.18 Chrome/128.0.6613.162 Electron/32.1.2 Safari/537.36
**Env**: electron
**Browser**: Chrome

this version is not fixed.

**Comment by mietl** [comment]
> Fixed in the next release在下一版本中修复

0.0.1-alpha.18 没有修复他

**Comment by hyoban** [comment]
Do you mean that the deleted content still exists? I thought you were talking about the content not being updated. We cannot detect which entries should be deleted

**Comment by mietl** [comment]
> Do you mean that the deleted content still exists? I thought you were talking about the content not being updated. We cannot detect which entries should be deleted您的意思是已删除的内容仍然存在吗？我以为你在说内容没有更新。我们无法检测应该删除哪些条目

好的，我理解了，删除的内容确实存在，不过也没关系

**Comment by mietl** [comment]
现在可以得到新的内容了。
